kind: pipeline
type: docker
name: default


steps:
  - name: install dependencies and build
    image: node
    commands:
      - npm install
      - npm run build
    volumes:
    - name: buildFiles
      path: /drone/src/build
  
  - name: upload to s3
    image: plugins/s3
    volumes:
    - name: buildFiles
      path: /drone/src/build
    settings:
      bucket: drone-test-react
      region: ap-southeast-2
      access_key:
        from_secret: access_key
      secret_key:
        from_secret: secret_key
      source: build
      target: /

volumes:
- name: buildFiles
  temp: {}