kind: pipeline
name: default

steps:
    - name: upload
      image: plugins/s3
      settings:
        bucket: drone-test-react
        region: ap-southeast-2
        access_key:
          from_secret: access_key
        secret_key:
          from_secret: secret_key
        source: build/*
        target: /*
